### ISSUE TITLE
update-deps seems not implemented

### ISSUE THREAD

**Issue by elstak** [bitovi/github-actions-deploy-eks-helm#21]
In my `Chart.yaml` I have defined the following dependency:
```yaml
dependencies:
  - name: mongodb
    version: ">= 10.26.3"
    repository: https://charts.bitnami.com/bitnami
```

However, when I use this action helper to deploy it, I get the following error:
```
Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: mongodb
```

By default `update-deps` is enabled, but I don't see it is implemented in `deploy.sh` script. Should script run `helm dependency update` in the chart directory?
