### ISSUE TITLE
can you add helm list action

### ISSUE THREAD

**Issue by sushovan23** [bitovi/github-actions-deploy-eks-helm#27]
Can helm list action be added to verify the installation? or any workaround available to achieve that?

**Comment by LeoDiazL** [comment]
Hey @sushovan23 

We have an update in the PR https://github.com/bitovi/github-actions-deploy-eks-helm/pull/28 to this action in order to support the helm list command. 

You can test it out by changing your workflow yaml line to use a specific branch like this

```
    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@27-add-helm-list-action
```

And set it up like the example in the [README file in that branch](https://github.com/bitovi/github-actions-deploy-eks-helm/blob/27-add-helm-list-action/README.md#example-list). You can use the `name` attribute to filter your results.

Let us know how it goes! Thanks!

**Comment by sushovan23** [comment]
@LeoDiazL Thanks for the quick turnaround. 

I'm facing following issue:
```
      - name: List Helm Release
        uses: bitovi/github-actions-deploy-eks-helm@27-add-helm-list-action
        with:
          aws-region: eu-west-1
          action: list
          cluster-name: Test
          namespace: test-ns
          name: app-test
          atomic: true
          timeout: 60s
 ```         
 
 /usr/local/bin/deploy: line 160: [: missing `]'
Error:  HELM_ACTION specified doesn't exist in this context. Please use 'install','uninstall' or 'list'

It's weird since error message says its there but doesn't look like it read it
