### ISSUE TITLE
update action Node.js version to 16

### ISSUE THREAD

**Issue by smallfish06** [bitovi/github-actions-deploy-eks-helm#29]
As Node.js 12 actions are deprecated seems like we need action to use Node.js 16

when running [github-actions-deploy-eks-helm](https://github.com/bitovi/github-actions-deploy-eks-helm) below warning occurs

> Please update the following actions to use Node.js 16: aws-actions/configure-aws-credentials@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

configure-aws-credentials has recently released v2 using node 16
https://github.com/aws-actions/configure-aws-credentials/commit/59e17413a1883ebd0a4c9340c5d5a348fbc9d9ee

Can it be possible?

**Comment by LeoDiazL** [comment]
Hi @smallfish06 !

Thanks for opening an issue with us. We are always happy to help.

Looks like you are using the configure-aws-credentials action like in the example below.

## Example 4 - Separate AWS login
```yaml
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ env.aws-account-id }}:role/${{ env.aws-assume-role }}
        aws-region: ${{ env.aws-region }}

    - name: Install Helm Chart
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.3
      with:
        aws-region: ${{ env.aws-region }}
        cluster-name: eks-cluster-${{ env.environment }}
        ... (put your other arguments here)
```

By just updating that `uses: aws-actions/configure-aws-credentials@v1` to `v2` should do it. 

If that's not the case, let us know. 

(And if you can provide some logs or a url to check, better. Thanks!)
