### ISSUE TITLE
How do you use helm secrets plugin with github-actions-deploy-eks-helm?

### ISSUE THREAD

**Issue by trjate** [bitovi/github-actions-deploy-eks-helm#36]
I'd like to use the helm secrets plugin and sops to decrypt a secrets.yaml (values) file before deploying, but I'm not sure how to do that.

https://github.com/jkroepke/helm-secrets

```
~/developer/capco/resourcing/helm github-actions-self-hosted-runner* ❯ ls
Chart.yaml   secrets.yaml values.yaml
```

```  
name: Deploy Helm
    uses: bitovi/github-actions-deploy-eks-helm@v1.2.4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: eu-west-1
      cluster-name: eks-staging-v2
      name: test
      namespace: test
      config-files: helm/values.yaml
      chart-path: xxxxxxx/xxxxxxxx
      chart-repository: 'https://xxxxxxxxxxxxxxxxxxxx/main'
      password: ${{ secrets.HELM_CHARTS_ACCESS_TOKEN }}
      username: xxxxxxxxxxxxx
      dry-run: true
      atomic: true
```
