### ISSUE TITLE
Unable to use environment variables in the values field 

### ISSUE THREAD

**Issue by JamesCalleja** [bitovi/github-actions-deploy-eks-helm#37]
Environment variables are being taken as literal  strings rather than interpolating the values to be passed in. 

It would be extremely useful to be able to make use of environment variables when using this action. 

For example if I wanted fetch and use the most recent image tag and use it and a environment values field. 

    - name: Get latest tag
      id: get_latest_tag
      run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags)
          
    - name: Install Helm Chart
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.4
      env:
        IMAGE_TAG: ${{ steps.get_latest_tag.outputs.tag }}
      with:
        aws-region: eu-west-2
        cluster-name: ${{ vars.ENV }}-k8s-cluster
        name: *********
        namespace: ********
        chart-path: ./build/helm
        config-files: ./build/helm/values.yaml
        values: image.app=1234567890.dkr.ecr.eu-west-2.amazonaws.com/xxxxxxxx-portal:$IMAGE_TAG
        timeout: 600s

**Comment by LeoDiazL** [comment]
Hi @JamesCalleja ! Thanks for opening an issue. 

Without going to the code, have you tried setting the workflow in this way? 

```
- name: Get latest tag
  id: get_latest_tag
  run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags)
      
- name: Install Helm Chart
  uses: bitovi/github-actions-deploy-eks-helm@v1.2.4
  with:
    aws-region: eu-west-2
    cluster-name: ${{ vars.ENV }}-k8s-cluster
    name: *********
    namespace: ********
    chart-path: ./build/helm
    config-files: ./build/helm/values.yaml
    values: image.app=1234567890.dkr.ecr.eu-west-2.amazonaws.com/xxxxxxxx-portal:${{ steps.get_latest_tag.outputs.tag }}
    timeout: 600s   
```

Let me know if that helps you solve your issue, if not, would love to have more details of what you see in the logs. 

Leo
