### ISSUE TITLE
helm-extra-args not working?

### ISSUE THREAD

**Issue by arseny-zinchenko** [bitovi/github-actions-deploy-eks-helm#41]
Adding `helm-extra-args` to a Step does nothing:

```
    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.5
      with:
        cluster-name: atlas-eks-dev-1-27
        namespace: dev-testing-ns
        name: test-release
        #atomic: true
        values: image.tag=${{ needs.build-docker.outputs.image_tag }}
        timeout: 60s
        helm-extra-args: debug
```

Maybe because in the `action.yaml` it's set as ``inputs.helm-extra-args`, but in the `runs` it expects for the `HELM_EXTRA_ARGS: ${{ inputs.extra-args }}`?
