### ISSUE TITLE
Is it possible to use all value overrides as separate lines in the values input ?

### ISSUE THREAD

**Issue by vvmohan13** [bitovi/github-actions-deploy-eks-helm#44]
We have our workflow calling the github-actions-deploy-eks-helm action as below. 

```
- name: Helm release
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.7
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws_region }}
        cluster-name: ${{ inputs.cluster_name }}
        chart-repository: oci://xxxxxxxxxxxxxxx
        chart-path: ${{ inputs.helm_chart_repo }}
        namespace: ${{ inputs.environment }}
        values: |-
          api-service.enabled=true,
          api-service.namespace=${{ inputs.environment }},
          api-service.image.tag=${{ inputs.image_tag }}
        name: ${{ inputs.helm_release_name }}
        version: 0.1.0
        username: xxxxxxxxxxxx
        password: xxxxxxxxxxxx
        dry-run: true
        helm-extra-args: "--reuse-values"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
``` 
Is it possible to specify value overrides as multi-line as shown above or should it all be in one single line as:
```
values:   api-service.enabled=true,api-service.namespace=${{ inputs.environment }},api-service.image.tag=${{ inputs.image_tag }}
```
