### ISSUE TITLE
Issues with separate AWS login?

### ISSUE THREAD

**Issue by bennysp** [bitovi/github-actions-deploy-eks-helm#56]
Hi,

I am trying to use the "separate AWS login" method. I use this with other actions too, so it is a known method on my side too. When I go to use this method, I get this error:

```shell
NAME	VERSION	DESCRIPTION
Logging into kubernetes cluster cicd-sa
Updated context arn:aws:eks:us-east-1:***:cluster/cicd-sa in /github/home/.kube/config
Missing credentials to login to ECR registry
Executing: helm upgrade --install --timeout 0s --version 15.5.23 --dependency-update -n coder --create-namespace coder-db bitnami/postgresql 
Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials
```

Output of Run command:
```shell
Run bitovi/github-actions-deploy-eks-helm@v1.2.10
  with:
    aws-region: us-east-1
    cluster-name: cicd-sa
    chart-repository: oci://registry-1.docker.io/bitnamicharts/postgresql
    chart-path: bitnami/postgresql
    namespace: coder
    name: coder-db
    version: 15.5.23
    dry-run: false
    create-namespace: true
    action: install
    timeout: 0s
    update-deps: true
  env:
    AWS_ACCOUNT: ***
    AWS_REGION: us-east-1
    AWS_DEFAULT_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
```

Code:
```yaml
name: on deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'the target environment to deploy to'
        required: true
        type: environment

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  apply:
    runs-on: ['self-hosted']
    name: Install for PostrgeSQL and Coder apps to k8s 
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
      AWS_REGION: ${{ vars.AWS_REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/gha_oidc_coderdeploy
          aws-region: ${{ env.AWS_REGION }}

      - name: deploy helm chart to kubernetes
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.10
        with:
          aws-region: ${{ env.AWS_REGION }}
          cluster-name: ${{ vars.TARGET_CLUSTER }}
          chart-repository: oci://registry-1.docker.io/bitnamicharts/postgresql
          chart-path: bitnami/postgresql
          namespace: coder
          name: coder-db
          version: 15.5.23
          dry-run: false
```

Any ideas as to why I am see this error?
