### ISSUE TITLE
Unable to reference separate GitHub repo as chart-path

### ISSUE THREAD

**Issue by rkirimov** [bitovi/github-actions-deploy-eks-helm#58]
I have my application in one GitHub repo and helm chart in another. Both repos are under the same org and both are private. In my github action, I checkout application repo, then inside of it checkout helm chart repo. Here's what it looks like:

```
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout helm-charts
        uses: actions/checkout@v4
        with:
          repository: my-org/helm-charts
          ref: "main"
          token: ${{ secrets.TOKEN }}
          path: charts/

      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.10
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          cluster-name: cluster
          config-files: values.yaml
          chart-path: charts/my-chart/
          namespace: my-ns
          name: my-app
```

Helm fails to install with the following:

```
Executing: helm upgrade --install --timeout 0s   -f values.yaml --dependency-update -n my-ns --create-namespace my-app charts/my-chart/ 
Error: repo charts not found
```
