### ISSUE TITLE
Unable to pull private ECR repository when referenced as a dependency

### ISSUE THREAD

**Issue by joechchung** [bitovi/github-actions-deploy-eks-helm#62]
I'm trying to deploy my local `Chart.yaml` but it has a dependency reference to a private ECR registry:

```
# build/helm/Chart.yaml
apiVersion: v2
name: api
version: 1.0.0
type: application

dependencies:
  - name: <ecr name>
    version: 1.0.0
    repository: "oci://<masked>.dkr.ecr.eu-west-2.amazonaws.com"
```

Even though i'm assuming a role and logging into ECR:

```
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: <role arn>
        aws-region: eu-west-2

    - name: Login to New Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Install Helm Chart
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
      with:
        chart-path: ./build/helm
```

I receive this error: `pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials`
